PACKAGE_NAME="netdisplay-power"
PACKAGE_VERSION="0.1.0"
BUILT_MODULE_NAME[0]="netdisplay_power"
DEST_MODULE_LOCATION[0]="/updates/dkms"
AUTOINSTALL="yes"
MAKE[0]="make KERNEL_DIR=/lib/modules/${kernelver}/build"
CLEAN="make KERNEL_DIR=/lib/modules/${kernelver}/build clean"
